"""empty message

Revision ID: 4a6e934c58c7
Revises: 
Create Date: 2023-03-13 02:58:33.263224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a6e934c58c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['tweets.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('username', 'conversation_id')
    )
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_username', sa.String(length=32), nullable=False))
        batch_op.drop_constraint('tweets_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'authors', ['author_username'], ['username'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', mysql.VARCHAR(length=32), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tweets_ibfk_1', 'authors', ['author_id'], ['username'])
        batch_op.drop_column('author_username')

    op.drop_table('conversations')
    # ### end Alembic commands ###
