"""empty message

Revision ID: cde895bb9834
Revises: e9872ee29c17
Create Date: 2023-03-13 12:00:00.880875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde895bb9834'
down_revision = 'e9872ee29c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tweets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('author_username', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['author_username'], ['authors.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('last_update', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['authors.username'], ),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('conversations',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['tweets.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('username', 'conversation_id')
    )
    op.create_table('replies',
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['tweets.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('conversations')
    op.drop_table('users')
    op.drop_table('tweets')
    op.drop_table('authors')
    # ### end Alembic commands ###
